kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node
  commands:
  - npm ci

- name: test
  image: node
  depends_on:
  - install
  commands:
  - npm run test

- name: lint
  image: node
  depends_on:
  - install
  commands:
  - npm run lint

- name: npm
  image: node
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  depends_on:
  - test
  - lint
  commands:
  - npm whoami
  - npm publish
  when:
    event:
    - tag